name: Ticket Infra Automation

on:
  issues:
    types: [opened]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Extract Variables From Issue Body
        run: |
          echo "TICKET_ID=ISSUE-${{ github.event.issue.number }}" >> $GITHUB_ENV

          BODY="${{ github.event.issue.body }}"

          INSTANCE_TYPE=$(echo "$BODY" | grep instance_type | cut -d'=' -f2)
          INSTANCE_COUNT=$(echo "$BODY" | grep instance_count | cut -d'=' -f2)

          # Validation
          if [ -z "$INSTANCE_TYPE" ]; then
            echo "ERROR: instance_type not provided in issue body"
            exit 1
          fi

          if [ -z "$INSTANCE_COUNT" ]; then
            echo "ERROR: instance_count not provided in issue body"
            exit 1
          fi

          # Guardrail (max 5 servers)
          if [ "$INSTANCE_COUNT" -gt 5 ]; then
            echo "ERROR: Maximum 5 servers allowed"
            exit 1
          fi

          echo "INSTANCE_TYPE=$INSTANCE_TYPE" >> $GITHUB_ENV
          echo "INSTANCE_COUNT=$INSTANCE_COUNT" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="instance_type=${{ env.INSTANCE_TYPE }}" \
            -var="instance_count=${{ env.INSTANCE_COUNT }}" \
            -var="ticket_id=${{ env.TICKET_ID }}"
